#!/bin/sh
#
# Author: Lu Xu <oliver_lew at outlook at com>
# License: MIT License. 2020-2021 Lu Xu
#
# A shell script to parse Shadowsocks(R)/v2ray subscription links
# and generate json config files
#
# Requirements: base64, curl/wget (optional)

local_port=${LOCAL_PORT:-1080}
timeout=${TIMEOUT:-300}

decode_base64() {
	case "$((${#1} % 4))" in
		2) echo "$1==" ;;
		3) echo "$1=" ;;
		*) echo "$1" ;;
	esac | tr '_-' '/+' | grep -o "^[a-zA-Z0-9+/=]*" | base64 -d
}

decode_ss() {
	IFS=:@\  read -r method password server server_port <<- EOF
		${1%%/?*}
	EOF
	conf=$(echo "ss-${server:-NoServer}-${server_port:-NoPort}.json" | tr "/ " _)
	echo "Saving to $conf"
	cat > "$conf" <<- EOF
	{
	    "server": "$server",
	    "server_port": $server_port,
	    "password": "$password",
	    "local_address": "127.0.0.1",
	    "local_port": $local_port,
	    "timeout": $timeout,
	    "method": "$method",
	}
	EOF
}

decode_ssr() {
	IFS=:\  read -r server server_port protocol method obfs password <<- EOF
		${1%%/?*}
	EOF

	while IFS='=' read -r key value; do
		[ -n "$value" ] && eval "$key=$(decode_base64 "$value")"
	done <<- EOF
		$(echo "${1#*/?}" | tr '&' '\n')
	EOF

	conf=$(echo "ssr-${group:-NoGroup}-${remarks:-Null}.json" | tr "/ " _)
	echo "Saving to $conf"
	cat > "$conf" <<- EOF
	{
	    "server": "$server",
	    "server_port": $server_port,
	    "password": "$(decode_base64 "$password")",
	    "local_address": "127.0.0.1",
	    "local_port": $local_port,
	    "timeout": $timeout,
	    "method": "$method",
	    "protocol": "$protocol",
	    "protocol_param": "${protoparam:-null}",
	    "obfs": "$obfs",
	    "obfs_param": "${obfsparam:-null}"
	}
	EOF
}

decode_vmess() {
	while IFS=': ' read -r key value; do
		[ -n "$value" ] && eval "$key=\"$value\""
	done <<- EOF
		$(echo "$1" | tr '{,}' '\n' | tr -d '"')
	EOF
	conf=$(echo "v2ray-${add-null}-${ps-null}.json" | tr "/ " _)
	echo "Saving to $conf"
	echo "$1" > "$conf"
}

decode_link() {
	info=$(decode_base64 "${1#*://}")
	case "${1%%:*}" in
		ss)     decode_ss "$info" ;;
		ssr)    decode_ssr "$info" ;;
		vmess)  decode_vmess "$info" ;;
		https?) decode_link "$(curl -Ss "$1" || wget -qO - "$1")" ;;
		*)      for link in $info; do decode_link "$link"; done ;;
	esac
}

if [ "$#" = 0 ]; then
	while read -r url; do
		decode_link "$url"
	done
elif [ "$#" = 1 ] && [ "$1" != "-h" ]; then
	decode_link "$1"
else
	echo "Usage: ssr-decode [ (http|ss|ssr|vmess):// | BASE64 | < input.txt ]"
fi

# vim: noet
